# Generated by Django 3.0.2 on 2020-02-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_auto_20200203_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='grade',
        ),
    ]
