# Generated by Django 3.0.2 on 2020-02-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='keyword',
        ),
    ]
