# Generated by Django 3.0.2 on 2020-03-02 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_album', '0002_auto_20200217_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcomment',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='keyword',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='keyword',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
